In [1]:
import numpy as np

In [2]:
print("NumPy Version:", np.__version__)


NumPy Version: 2.3.3


In [3]:
arr1 = np.arange(1, 11)
reshaped_arr1 = arr1.reshape(2, 5)
print("reshaped Array\n" , reshaped_arr1)

reshaped Array
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
arr2 = np.arange(1, 21)
subset_arr2 = arr2[5:16]  
print("original array\n", arr2)
print("extracted array\n", subset_arr2)

original array
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
extracted array
 [ 6  7  8  9 10 11 12 13 14 15 16]


In [5]:
mean_val = np.mean(arr2)
median_val = np.median(arr2)
std_val = np.std(arr2)
print("\nMean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)


Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


In [6]:
x = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 100, 110, 120]])

y = np.array([1, 2, 3, 4])

result= x-y
print(" array (x):\n", x)
print("array (y):\n", y)
print("Result\n", result)


 array (x):
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
array (y):
 [1 2 3 4]
Result
 [[  9  18  27  36]
 [ 49  58  67  76]
 [ 89  98 107 116]]
